### ISSUE TITLE
Accomodate peertube as well

### ISSUE THREAD

**Issue by mmahmoudian** [TheKinrar/instances#107]
Peertube has also "similar" structure as Mastodon, each instance has its own Code of Conduct and can have language and registration preferences and configurations, therefore very similar software as you have here can be also used for Peertubes. For instance, take a look at this About page:

https://peertube.linuxrocks.online/about/instance

**Comment by TheKinrar** [comment]
Duplicate of #51

**Comment by mmahmoudian** [comment]
Thanks :+1: . Sorry for the duplicate. it was an oversight from my side.
