### ISSUE TITLE
Pleroma versions

### ISSUE THREAD

**Issue by tusooa** [TheKinrar/instances#108]
Pleroma has a version string in /api/v1/instance that looks like:

```
"version": "2.7.2 (compatible; Pleroma 2.4.3-0-gaa31f7a19)"
```

( https://docs-develop.pleroma.social/backend/development/API/differences_in_mastoapi_responses/ )

**Comment by tusooa** [comment]
Although some days ago I dreamed about this being fixed, it hasn't.

**Comment by TheKinrar** [comment]
Duplicate of #51
