### ISSUE TITLE
Feature: get instances.social link included in Mastodon

### ISSUE THREAD

**Issue by AMDphreak** [TheKinrar/instances#112]
Mastodon is supposed to connect people. How can people feel connected when they're unaware that Mastodon has many instances? Mastodon can't hope to ever grow when it does not make it obvious to new users that they are signing up and seeing just a single instance. The interconnected nature of Mastodon instances should be an integral part of the browsing experience. A map of Mastodon instances should be included in the Mastodon interface at the top, providing a top-down overview of the Mastodon communities.

**Comment by TheKinrar** [comment]
Issues regarding the Mastodon software should go to https://github.com/tootsuite/mastodon. I also believe Mastodon already includes a link to joinmastodon.org wich is another, curated, but way more user-friendly instances list.
