### ISSUE TITLE
mstdn.science missing - maybe add contact form to submit missing instances?

### ISSUE THREAD

**Issue by corneliusroemer** [TheKinrar/instances#120]
I was wondering why my instance mstdn.science isn't showing up.

How do you scrape for new instances? How long does it take for them to show up?

**Comment by coffeecult** [comment]
actually,
i have an old instance..
still no show :(
just saying in case it aint a new/old bug.
cheers!

**Comment by booth-f** [comment]
Puppo Space is also missing from the instance list and we have been around since 2018 :(

**Comment by MrGeneration** [comment]
They don't scrape of actively look for instances.
Instance owners can register their instance themselves:
https://instances.social/admin

So it's an admin based opt in.

**Comment by TheKinrar** [comment]
It is indeed supposed to discover new instances, but it was broken. It's fixed now, so new instances should appear.
