### ISSUE TITLE
Moderation filter removed

### ISSUE THREAD

**Issue by Joeviocoe** [TheKinrar/instances#130]
https://github.com/TheKinrar/instances/commit/2987445ee1068580de62379160e8494c00da1aee

> Remove moderation filters from wizard and lists
> These were completely broken, and weird, tbh.

Many, many people are wanting to move from Twitter to Mastodon and to use your search engine to find a suitable instance.
This guide shows a key feature...
https://www.tomshardware.com/how-to/move-from-twitter-to-mastodon
... to be able to filter based on moderation rules is crucial.  Please prioritize.

**Comment by TheKinrar** [comment]
I understand how filtering by moderation rules is important, but the old filter was quite bad I think? I'd like to find a new, better way to do this. At least, changing the list of filters would be great.

This being said, I think you're right, it's not great to remove it altogether. I'm reverting it until I find a better approach.

**Comment by Joeviocoe** [comment]
Thank you.
