### ISSUE TITLE
"Generalistic" is super awkward 

### ISSUE THREAD

**Issue by scottdotjs** [TheKinrar/instances#133]
It would look better if you said "general" which is already an adjective. 🙂

**Comment by xgpt** [comment]
Agreed

**Comment by TheKinrar** [comment]
I'll do it at some point but feel free to do a PR for this too! I know the project is not very welcoming for contributors in its current state, but changing this is basically about replacing occurrences of "generalistic" with "general" so it's not that bad

**Comment by xgpt** [comment]
I'll see if I can get to it tonight!
