### ISSUE TITLE
Not Recognizing my Mastodon Server

### ISSUE THREAD

**Issue by SecureCPU** [TheKinrar/instances#135]
I'm trying to add my Mastodon Server and sign up. but everytime I try I get the following error:

Sign up failed. It looks like this instance is not a Mastodon or Pleroma instance. Other fediverse instances can show up on instances.social but are not (yet) compatible with this admin space.

My Mastodon server is securecpu.social

Can anyone help me figure out why?

Thanks!

**Comment by TheKinrar** [comment]
I just tried visiting your instance and got a 522 error from Cloudflare
