### ISSUE TITLE
Admin space not updating

### ISSUE THREAD

**Issue by chenew** [TheKinrar/instances#145]
About a couple weeks ago, I’ve updated my instance’s info in the admin space, including the short and full description, topic, category, and language. Confirmed the option to hide my instance is not selected. Checked today and the info hasn’t updated on the public site when I search for my instance using the wizard. The connection status does say it was last checked today.

Instance name: techy.social

**Comment by TheKinrar** [comment]
The instance page now uses the description provided in the instance settings via its API, but I see Mastodon has actually recently removed the full description from the API (https://github.com/mastodon/mastodon/pull/19294).
I guess instances.social will need to either start using the descriptions from the admin space again, or only show short descriptions.

**Comment by TheKinrar** [comment]
The instance page now uses the description provided in the instance settings via its API, but I see Mastodon has recently changed the API for getting the description. I'll fix that, and remove the useless settings from the admin space.

**Comment by TheKinrar** [comment]
Should be ok now
