### ISSUE TITLE
Instances advertising wrong figures

### ISSUE THREAD

**Issue by mauforonda** [TheKinrar/instances#147]
Occasionally some instances will advertise wrong figures. A couple I found today:

- [bz.pawdev.me](https://bz.pawdev.me) grew 90k users on February 10 at midnight (UTC). It claims to have 91k users [in the mastodon compatible endpoint](https://bz.pawdev.me/api/v1/instance), but has only 30 according to [its calckey endpoint](http://bz.pawdev.me/api/charts/users?limit=30&span=day).
- A similar situation with [ck.borgar.space](https://ck.borgar.space/). It went from 2 to 10k users at around 21:00 (UTC) on February 10. Its [mastodon endpoint](https://ck.borgar.space/api/v1/instance) tells a completely different story from [its calckey endpoint](https://ck.borgar.space/api/charts/users?limit=30&span=day)

I guess these will go into some blacklist. Is this the best place to report such cases?

**Comment by mauforonda** [comment]
Another one:

- [jo-dev.xyz](https://jo-dev.xyz/) went from 2 to 512 users on February 10 at around 21:00 (UTC). Its [mastodon endpoint](https://jo-dev.xyz/api/v1/instance) currently lists over 600 users while [calckey](https://jo-dev.xyz/api/charts/users?limit=30&span=day) claims just 3. 

I just checked if this was an issue in [calckey](https://codeberg.org/calckey/calckey/), but the [source](https://codeberg.org/calckey/calckey/src/branch/main/packages/backend/src/server/api/endpoints/compatibility/instance-info.ts) is clearly trying to fill this value with the number of local users and the [reference implementation](https://calckey.social/) is [working](https://calckey.social/api/v1/instance) [fine](https://calckey.social/api/charts/users?limit=30&span=day). So this is likely some bulshit done by these specific instances.

**Comment by mauforonda** [comment]
More:

- [mk.pupbrained.xyz](https://mk.pupbrained.xyz)
- [stop.voring.me](https://stop.voring.me)
- [kids.0px.io](https://kids.0px.io)
- [electricrequiem.com](https://electricrequiem.com)

Same story as the previous ones.

**Comment by TheKinrar** [comment]
It's indeed a Calckey issue. https://codeberg.org/calckey/calckey/issues/9637
I've blacklisted Calckey for now.

**Comment by TheKinrar** [comment]
Thanks for reporting this! :)
