### ISSUE TITLE
Mastodon server is not recognised

### ISSUE THREAD

**Issue by iOSDevil** [TheKinrar/instances#148]
I'm trying to add my Mastodon Server and sign up, I get the following error:

Sign up failed. It looks like this instance is not a Mastodon or Pleroma instance. Other fediverse instances can show up on instances.social but are not (yet) compatible with this admin space.

My Mastodon server is fpl.social

Can anyone help me figure out why?

**Comment by TheKinrar** [comment]
Please try again and reopen if it still happens.
