### ISSUE TITLE
Instance not recognized 

### ISSUE THREAD

**Issue by fouroclockfarms** [TheKinrar/instances#149]
getting this message for my instance, which is running mastodon 4.1.0

"Sign up failed. It looks like this instance is not a Mastodon or Pleroma instance."

**Comment by michaelband** [comment]
Experiencing the same issue

**Comment by zuhairmahd** [comment]
Same here

**Comment by litten2up** [comment]
same, mine is in the list, tho marked as down due to a sql error (thats now fixed), but try adding https:// infront of your instance name sense that gives a different error

![image](https://user-images.githubusercontent.com/55027142/220990356-c92071ce-7f0a-46a9-99ec-e2694e076eae.png)

**Comment by TheKinrar** [comment]
Actually, it should be fixed now, so please try again and reopen if it's still broken.

**Comment by zuhairmahd** [comment]
@TheKinrar  orio.zuhairmahmoud.com.

Thanks.
