### ISSUE TITLE
Unable to sign up my instance

### ISSUE THREAD

**Issue by ghstwhl** [TheKinrar/instances#151]
I've spun up an instance at https://besties.com and it has had users successfully join, and can connect with identities on other servers, and posts on the server can be seen on other servers by following users.  But when I try to sign up my instance at https://instances.social/admin I receive the following message:  "Sign up failed. Instance not found. If it was just created, make sure it is reachable from other instances then wait for 24 hours. If it still does not work, please open an issue on GitHub (see footer). "

Is there something I have failed to configure correctly?

**Comment by ghstwhl** [comment]
I am now receiving the message "Sign up failed. It looks like this instance is not a Mastodon or Pleroma instance. Other fediverse instances can show up on instances.social but are not (yet) compatible with this admin space." 

I am running Mastadon version 4.1.0

**Comment by litten2up** [comment]
with your different errors, they seem to occure depending on if you have https:// in the url

**Comment by ghstwhl** [comment]
> with your different errors, they seem to occure depending on if you have https:// in the url

Yes,  tried it both ways, because I looked through the issues here and someone suggested that it might make a difference.

As it is, besties.com is showing up in the searchable list at https://instances.social/ but I am unable to sign up in the admin space.

**Comment by TheKinrar** [comment]
Should be ok now!
