### ISSUE TITLE
Instances being marked as "Down" due to lookup timeout

### ISSUE THREAD

**Issue by AverageMarcus** [TheKinrar/instances#153]
I'm fairly sure the latest change to IPv6 checking has caused instances to sometimes (but not always) be marked as "Down" due to the lookup failing.

For example, my instance `k8s.social` is currently showing as DOWN - https://instances.social/k8s.social - but this is certainly not the case. 

Looking at the instance log it is filled with entries such as:
```
[Sun, 19 Mar 2023 08:46:07 GMT] [ERROR] Could not get instance info: "Timeout awaiting 'lookup' for 10000ms".
```

I believe (but not certain) that the problem is due to the IPv6 nameservers being used here: https://github.com/TheKinrar/instances/blob/11ae7c325b8d4b22000145b1ffca990ed1fbfa39/helpers/got.js#L20-L21

If I understand correctly the IPs for IPv6 should be wrapped in `[]`. That is at least the impression I get from the [Node.js docs](https://nodejs.org/api/dns.html#dnssetserversservers). If the servers are used in a random / round-robin fashion this would explain why the results are only working some of the time and not others (e.g. the IPv4 endpoints work, the IPv6 just timeout).

**Comment by louis77** [comment]
Same problem here. I've tried to contact the maintainer over Fediverse multiple times without response. Our site (emacs.ch) is marked down for a while now and we receive basically near-zero signups ever since. Our instance has 100% uptime since its inception. Our certificate is rates "F" despite being up to date and perfectly valid.

**Comment by vmstan** [comment]
Noticing a similar issue here. We actually advertise that we "have better than 99.9% uptime on Instances.social" and then I go look and we're at 95% -- except, of course we're not.

**Comment by daenney** [comment]
I submitted a PR to wrap the IPv6 address in `setServer` in `[]`, but I'm not sure that's the fix. The NodeJS docs do show that call consistently with the brackets around it, but it also says is accepts any valid RFC5952 notation and as long as the port number is not provided it shouldn't require the brackets.

However, when I dug into the NodeJS code I found https://github.com/nodejs/node/blob/38b6ecc12e9d3458205da8c4c698cf127590c8b6/lib/internal/dns/utils.js#L111. I might be looking in the wrong place but it seems to be using a regex there to determine if it's IPv6 or not, and that regex wants brackets. There's an `isIP` check that happens earlier that seems to use a different IPv6 regex. I'm not entirely sure of how all that code flows but the whole regex based validation looks dodgy and it wouldn't surprise me if wrapping it in brackets does fix it.

One other thing. Looking at `instances.social`, it does not publish a AAAA record. This suggests the instance itself might not have IPv6 connectivity, which could explain the connect timeout though I would hope that a lack of dualstack support on the instance would raise an error earlier than waiting on the connection to timeout. It's also possible the scans run from other instances entirely which do have IPv6 support but that's hard for me to divinate.

**Comment by miyurusankalpa** [comment]
@daenney your fix might work, it is the workaround I use on my [IPv6 DNS proxy project.](https://gitlab.com/miyurusankalpa/IPv6-dns-server/-/blob/master/app.js#L35-L36)

**Comment by louis77** [comment]
I've tried to contact the project admin several times. He promised to look into it and remove the down-logs. While our instance appears now as "online" the uptime is "80%" (while in fact we have at least 99.9%) and the certificate is marked "F" for no explanation. 

This sucks big time.

**Comment by TheKinrar** [comment]
Hey there. I've not been able to look into that as I've been busy in the last two weeks with some important problems in my personal life, but I'm now back home so I'm looking into it right now.

Quick notes for now:
- I can't really see why the IPv6 address notation would be responsible for it, you can request AAAA records from a IPv4 DNS server anyway
- The server does have an IPv6 address obviously, I've clearly made a mistake somewhere but it's not that stupid (I hope), especially considering it used to work

I'll let you know when it's sorted out.
