### ISSUE TITLE
Firefish instances reporting wrong stats

### ISSUE THREAD

**Issue by mauforonda** [TheKinrar/instances#165]
Since September 21, Firefish instances upgrading to [v1.0.4-beta3](https://git.joinfirefish.org/firefish/firefish/-/releases) have reported `user_count` and `status_count` figures corresponding to all their indexed instances. As a result, you see these [crazy spikes](https://mastodon.social/@mastodonusercount/111110575038417012) in fediverse user counts that are also being replicated in instances.social.

Some samples:

- https://transgirl.cafe
- https://drslump.canpavon.cat
- https://toot.phasorburn.com
- https://void.rehab

and many many more.

I've created [an issue in the firefish repo](https://git.joinfirefish.org/firefish/firefish/-/issues/10759), but while this bug persists, firefish instances should probably be filtered out from this index.

**Comment by TheKinrar** [comment]
Thanks for reporting this. It's nothing new - it was already the case in March when I blocked Calckey instances. See 28451b44b069c19fa37fb64b0fb503212d224fd5.
The project was renamed to Firefish and therefore the block didn't work anymore, this is now fixed.
I believe they had a comment on their issue 9637 about that at some point, maybe they lost it while migrating to their new issue tracker.
