### ISSUE TITLE
Unflag the not-dead instances

### ISSUE THREAD

**Issue by Sebbaz** [TheKinrar/instances#32]
When an instance is down during 2 weeks, it's flagged as dead.
Why not make the admin of the instance able to unflag his instance ?

For example, I was the single user of my instance, but during holidays, after a bug,  I shutdown the server. When I up Mastodon working again, the instance cannot be referenced again.

**Comment by lodart** [comment]
I have the same issue ! My instance is marked as down but is actually up : https://instances.social/pouet.space

**Comment by TheKinrar** [comment]
Fixed in 686573b973b056501a8ea933c6fef22e5274d0a6.
